### ISSUE TITLE
ITS A VIRUS!!

### ISSUE THREAD

**Issue by randomluisaa** [Stanley-GF/Discord-Nitro-Generator#10]
Who Replys got a small dick and is gay

**Comment by Stanley-GF** [comment]
proof ? its opensource bro, check the src code

**Comment by randomluisaa** [comment]
![grafik](https://user-images.githubusercontent.com/74919716/100001186-0c1c8380-2dc3-11eb-9513-286f431ffbef.png)

**Comment by Yarendra** [comment]
Thank you for your email ✌️☺️

**Comment by Stanley-GF** [comment]
@randomluisaa u are really retard i think. I dont know how resp u else ur a fucking retard check the source code

**Comment by SushiMan-o3** [comment]
@Stanley-GF did these people make a github account just to comment that it was a virus, or they don't know how to use it🤣. Also, you can make a repl instead of getting them to download visual studios and stuff cause it's obvious they don't know what source code is. (btw I cant find your discord acc).

**Comment by Stanley-GF** [comment]
Hi sushi,
True.
U can add me with they discord :
Stan#1337
Stan#4444
Stan#1111
Stan#4321
Stan#9999
Stan#2222

Im actually In Stan#1337, other is if i get ban.

**Comment by Flare404** [comment]
> Stan#1337

never seen so many backup accounts

**Comment by StanBarkmeijer** [comment]
@Stanley-GF If you could maybe remove the Stan#999 from that list, that's my Discord account. I keep receiving messages from people that need support, even though I have nothing to do with this 🤣 

![image](https://user-images.githubusercontent.com/31732012/102469150-b00bee80-4052-11eb-8cc3-441feee24733.png)

**Comment by Stanley-GF** [comment]
yeah sorry i lose this # !

**Comment by Risewill23** [comment]
Looks Safe To Me

**Comment by Sunnyboii411** [comment]
jesus how can be someone this retarded....

**Comment by C0V1D-19** [comment]
# A open source virus..... 
## tell yourself whatever you want lmao
