### ISSUE TITLE
Does it work on mac 

### ISSUE THREAD

**Issue by hello391** [Stanley-GF/Discord-Nitro-Generator#11]
when I downloaded it and tried to open it said "window files are not supported" is there anything I can do

**Comment by AstroOrbis** [comment]
bump

**Comment by AstroOrbis** [comment]
nvm I mean you can do it in a VM like vmWare Fusion or VirtualBox or Parallels

**Comment by Nachoman109** [comment]
you  can use wine or PlayonMac to open windows files without using virtualbox
