### ISSUE TITLE
Virus. Here’s why

### ISSUE THREAD

**Issue by DaEpicSwag** [Stanley-GF/Discord-Nitro-Generator#14]
After seeing many compliants about this i tool matters into my own hands. Since the source code was clean, i relized the dll was doing the junky stuff. Decompile it and boom. It is a virus lol.

**Comment by Stanley-GF** [comment]
stupid, caps

**Comment by DaEpicSwag** [comment]
Bro you know that this is a virus. Own up to it.

**Comment by endlessXD** [comment]
wallah bro

**Comment by AstroOrbis** [comment]
Time for a virustotal

**Comment by ICExFS** [comment]
lmao guys its open source-

**Comment by DaEpicSwag** [comment]
Are the dlls open source? Didn’t think so

**Comment by DaEpicSwag** [comment]
Don’t mean anything. Virus total is crap and my malware flies through that like a champ

**Comment by ICExFS** [comment]
why tf yall using virus total just  check the code lmao?

**Comment by ICExFS** [comment]
lmfao

**Comment by ICExFS** [comment]
I just readed the code and my dude's using his own token, so if you found any hits it'll reedem the nitro on his account. You can see on the check void that he's using an Authorization header with a token

**Comment by AstroOrbis** [comment]
Ok then what’s his token? That would be a token leak anyways smh

**Comment by ICExFS** [comment]
Just go to the check void

**Comment by AstroOrbis** [comment]
Which file?

**Comment by ICExFS** [comment]
check yourself

**Comment by AstroOrbis** [comment]
Cap

**Comment by ICExFS** [comment]
CheckerHelper.cs 
Line ~150

**Comment by ICExFS** [comment]
Line 140*

**Comment by AstroOrbis** [comment]
Not there (wink wink token nuke time)

**Comment by ICExFS** [comment]
lmfao man common ![image](https://user-images.githubusercontent.com/73942099/111915357-e52b4100-8a86-11eb-95c8-2f6df46bbfc3.jpeg)

**Comment by Stanley-GF** [comment]
Gg Sherlock look the token hes not workin' it was for test an autoclaimer.

**Comment by ICExFS** [comment]
mdddrrrr oui jpp y'a personne qui la vue
