### ISSUE TITLE
Is this thing rlly safe to use? 

### ISSUE THREAD

**Issue by Manga-Man** [Stanley-GF/Discord-Nitro-Generator#16]
Is this thing rlly safe to use? or its some kind of a virus?<br>
![image](https://user-images.githubusercontent.com/72046004/126574651-cde6d3a3-39e0-4649-8c99-cc3de4f190ba.png)

**Comment by Manga-Man** [comment]
I'm using chrome os btw

**Comment by PurpShell** [comment]
> Is this thing rlly safe to use? or its some kind of a virus?<br>
> ![image](https://user-images.githubusercontent.com/72046004/126574651-cde6d3a3-39e0-4649-8c99-cc3de4f190ba.png)
> 

Yes, it'll steal your account

**Comment by Manga-Man** [comment]
lol, i guess?

**Comment by PurpShell** [comment]
I verified the integrity, and the one he gives you as a release is not the same as the one built from source. This shit is untrusted

**Comment by Stanley-GF** [comment]
Learn to verif, then. @PurpShell 
@Manga-Man do not trust kids who don't even know how to decompile something.

**Comment by Stanley-GF** [comment]
There no backdoor or anything. Issue closed reason useless.
