### ISSUE TITLE
HOW DO I OPEN AND USE IT

### ISSUE THREAD

**Issue by abhinandan221** [Stanley-GF/Discord-Nitro-Generator#4]
HOW DO I OPEN AND USE IT

**Comment by Stanley-GF** [comment]
Just download from releases :) [https://github.com/Stanley-GF/Discord-Nitro-Generator/releases/download/1.0.0/Discord.Nitro.Generator.V1.zip](url)

**Comment by johann-lau** [comment]
How do I use on Mac

**Comment by Stanley-GF** [comment]
i think i must remade it in NetCore :/

Le dim. 27 sept. 2020 à 15:01, johann-lau <notifications@github.com> a
écrit :
