### ISSUE TITLE
check command does not work

### ISSUE THREAD

**Issue by Voidoffi** [Stanley-GF/Discord-Nitro-Generator#8]

**Comment by randomluisaa** [comment]
Bro its a Virus called Trojan:Win32/Occamy.C2F

**Comment by Voidoffi** [comment]
> Bro its a Virus called Trojan:Win32/Occamy.C2F
> 
> 

Does it do anything to my computer ?

**Comment by Stanley-GF** [comment]
@randomluisaa can you stop spamming ? else i ban you from my github. Its not a virus. Its *open-source* (too advanced for a skid like u) so look the source code and say me after :)
