### ISSUE TITLE
How am I supposed to use this exactly? there are no instructions!

### ISSUE THREAD

**Issue by gnxrlyqf** [Stanley-GF/Discord-Nitro-Generator#9]

**Comment by AstroOrbis** [comment]
Download zip from releases

**Comment by ICExFS** [comment]
LMFAOOOO IT’S A VIRUS



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by AstroOrbis** [comment]
uh no i checked the source, its all fine... the only thing that might arise is virustotal might be confuzed about why we would need to get 200-PASS codes from HTML requests... and even
